version: '3.3'
services:
  post_db:
    image: mongo:3.2
    container_name: post_db
    volumes:
      - post_db:/data/db
    expose:
      - "27017"
    networks:
      - backend_nw
    container_name: db
  ui:
    build: ./ui
    image: ui:${VERSION}
    container_name: ui
    environment:
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9292
      - ZIPKIN_ENABLED=False
    ports:
      - "${UI_PORT}:9292/tcp"
    networks:
      - frontend_nw
    container_name: ui
  post:
    build: ./post-py
    image: post:${VERSION}
    container_name: post
    depends_on:
      - post_db
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE_PORT=27017
      - ZIPKIN_ENABLED=False
    networks:
      - frontend_nw
      - backend_nw
    container_name: post
  comment:
    build: ./comment
    image: comment:${VERSION}
    container_name: comment
    expose:
      - "9292"
    environment:
      - COMMENT_DATABASE_HOST=post_db
      - COMMENT_DATABASE_PORT=27017
      - COMMENT_DATABASE=comments
    networks:
      - frontend_nw
      - backend_nw
    container_name: comment

  prometheus:
    image: ${USER_NAME}/prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - frontend_nw
      - backend_nw

  node-exporter:
    image:  prom/node-exporter:v0.15.2
    user: root
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - frontend_nw
      - backend_nw

volumes:
  prometheus_data:
  post_db:

networks:
  frontend_nw:
  backend_nw:
